version: "3"

services:
  voyager:
    container_name: voyager
    image: registry.diginfra.net/vicd/voyager:latest
    volumes:
      - ./nc/html/data:/app/files # path to wd should be /app/files/${user}/files/models
    networks:
      - traefik-public
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.voyager.rule=Host(`viewer.${HOSTNAME}`)"
#      - "traefik.http.routers.voyager.entrypoints=http"
#      - "traefik.http.services.voyager.loadbalancer.server.port=8000"

  nc:
    container_name: nc
    image: registry.diginfra.net/vicd/nextcloud:latest
    depends_on:
      - voyager
    volumes:
      - ./nc/html:/var/www/html
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc.rule=Host(`files.${HOSTNAME}`)"
      - "traefik.http.routers.nc.entrypoints=http"
      - "traefik.http.services.nc.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true