version: '3.5'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    restart: always
    command:
      - "--api.dashboard=true"
      - "--api.insecure=flase"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${HOSTNAME}`)"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=mywhitelist@docker"
#      - "traefik.http.middlewares.mywhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 83.85.42.212, 192.87.139.238"
      - "traefik.http.middlewares.mywhitelist.basicauth.users=user:$$2y$$05$$zig/c1pe6XXAJXFBRzx6oeshIa7d3GuZuKaRTjegGbyCykZkXjYU6"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true