version: "3"

services:
  voyager:
    container_name: voyager
    image: registry.diginfra.net/vicd/voyager:latest
#    env_file:
#      - .env
    volumes:
      - ./files:/app/files
#    ports:
#      - "8000:8000"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voyager.rule=Host(`voyager.${USERNAME}.${HOSTNAME}`)"
      - "traefik.http.routers.voyager.entrypoints=http"
#      - "traefik.http.routers.voyager.service=voyager@internal"
      - "traefik.http.services.voyager.loadbalancer.server.port=8000"

  nc:
    container_name: nc
    image: registry.diginfra.net/vicd/nextcloud:latest
    depends_on:
      - voyager
    volumes:
      - ./nc/html:/var/www/html
      - ./files/models:/var/www/html/data/admin/files/Documents/models
#    docker exec -u www-data nc php occ maintenance:install --admin-user admin --admin-pass ba222ded25d957b900c03bef914333cd
#    docker exec -u root nc chown -R www-data:root /var/www/html/data/
#    docker cp files/models nc:/var/www/html/data/admin/files/Documents/models
#    docker exec -u www-data nc php occ files:scan admin
#    ports:
#      - "8080:80"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc.rule=Host(`nc.${USERNAME}.${HOSTNAME}`)"
      - "traefik.http.routers.nc.entrypoints=http"
#      - "traefik.http.routers.nc.service=nc@internal"
      - "traefik.http.services.nc.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true